In [2]:
a = np.array([1000,1010,1002])

In [3]:
a

array([1000, 1010, 1002])

In [4]:
a_max = np.max(a)

In [5]:
a_max

1010

In [6]:
sub_result = a-a_max

In [7]:
sub_result

array([-10,   0,  -8])

In [8]:
np.exp(sub_result)

array([4.53999298e-05, 1.00000000e+00, 3.35462628e-04])

In [9]:
def softmax(x):
    x=x-np.max(x)
    return np.exp(x) / np.sum(np.exp(x))

In [10]:
softmax(a)

array([4.53826452e-05, 9.99619282e-01, 3.35334911e-04])